FROM dpage/pgadmin4:6.3
COPY ./entrypoints/entrypoint_pgadmin4.sh entrypoint_pgadmin4.sh

USER root
RUN apk add bash
RUN ["chmod", "+x", "entrypoint_pgadmin4.sh"]
USER pgadmin

ENTRYPOINT ["./entrypoint_pgadmin4.sh"]
CMD ["default"]