FROM postgis/postgis:13-3.2

# Configure utils
RUN apt-get update \
    && apt-get install -y wget unzip apt-utils postgis \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Make data dir
RUN mkdir -p /gisdata \
	&& mkdir -p /gisdata/temp \
    && chmod 777 -R /gisdata \
    && chmod 777 -R /gisdata/temp

COPY ./init_files/initdb-postgis.sh /docker-entrypoint-initdb.d/10_postgis.sh
COPY ./init_files/load_tiger_data.sh /docker-entrypoint-initdb.d/11_load_data.sh